version: '3'

networks:
  default:
    driver: ${NETWORKS_DRIVER}

services:
  app:
    build: ./app
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./app/reflex.conf:/reflex.conf
    ports:
      - "${APP_HTTP_PORT}:8080"
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks:
      - default
